from django.urls import path
from .views import (
    TelemetryIngestView,
    IncidentIngestView,
    FallIncidentIngestView,
    AggressionIncidentIngestView,
    MobileDashboardView,
    MobileActivityLogView,
    MobileFacilityIncidentsView,
    GaitIngestView,
    GaitHistoryView,
    GaitAllResidentsView,
    AnalyzeVideoView,
    MealTimeListView,
    MealTimeCreateView,
    MealTimeDetailView,
    NotificationListView,
    NotificationMarkReadView,
    NotificationMarkAllReadView,
    IncidentListView,
    AbsenceCheckView,
    MealAttendanceStartView,
    MealAttendanceStopView,
    MealAttendanceStatusView,
    MealAttendanceAnalyzeFrameView,
    PersonCountView,
    VideoStreamView,
    IsolationSessionListView,
    IsolationVideoUploadView,
    IsolationSessionDetailView,
    AggressionStreamStartView,
    AggressionStreamStopView,
    AggressionStreamStatusView,
    aggression_stream_feed,
    meal_attendance_feed,
)

urlpatterns = [
    path('ingest/telemetry/', TelemetryIngestView.as_view(), name='ingest-telemetry'),
    path('ingest/incident/', IncidentIngestView.as_view(), name='ingest-incident'),
    path('ingest/fall/', FallIncidentIngestView.as_view(), name='ingest-fall'),
    path('ingest/aggression/', AggressionIncidentIngestView.as_view(), name='ingest-aggression'),

    # Mobile App API Endpoints (Secured via SimpleJWT)
    path('mobile/dashboard/', MobileDashboardView.as_view(), name='mobile-dashboard'),
    path('mobile/activity-log/', MobileActivityLogView.as_view(), name='mobile-activity-log'),
    path('mobile/facility-incidents/', MobileFacilityIncidentsView.as_view(), name='mobile-facility-incidents'),
    path('gait/ingest/', GaitIngestView.as_view(), name='gait-ingest'),
    path('gait/history/<int:resident_id>/', GaitHistoryView.as_view(), name='gait-history'),
    path('gait/all/', GaitAllResidentsView.as_view(), name='gait-all'),
    path('gait/analyze/', AnalyzeVideoView.as_view(), name='gait-analyze'),
    path('incidents/', IncidentListView.as_view(), name='incident-list'),
    path('meals/', MealTimeListView.as_view(), name='meal-list'),
    path('meals/create/', MealTimeCreateView.as_view(), name='meal-create'),
    path('meals/<int:meal_id>/', MealTimeDetailView.as_view(), name='meal-detail'),
    path('notifications/', NotificationListView.as_view(), name='notification-list'),
    path('notifications/<int:notification_id>/read/', NotificationMarkReadView.as_view(), name='notification-read'),
    path('notifications/read-all/', NotificationMarkAllReadView.as_view(), name='notification-read-all'),
    path('check-absences/', AbsenceCheckView.as_view(), name='check-absences'),
    path('meal-attendance/start/', MealAttendanceStartView.as_view(), name='meal-attendance-start'),
    path('meal-attendance/stop/', MealAttendanceStopView.as_view(), name='meal-attendance-stop'),
    path('meal-attendance/status/', MealAttendanceStatusView.as_view(), name='meal-attendance-status'),
    path('meal-attendance/analyze-frame/', MealAttendanceAnalyzeFrameView.as_view(), name='meal-attendance-analyze-frame'),
    path('meal-attendance/feed/', meal_attendance_feed, name='meal-attendance-feed'),
    path('person-count/', PersonCountView.as_view(), name='person-count'),
    path('video/stream/', VideoStreamView.as_view(), name='video-stream'),

    # Social Isolation Detection
    path('isolation/sessions/', IsolationSessionListView.as_view(), name='isolation-sessions'),
    path('isolation/sessions/<int:pk>/', IsolationSessionDetailView.as_view(), name='isolation-session-detail'),
    path('isolation/upload/', IsolationVideoUploadView.as_view(), name='isolation-upload'),

    # Live Aggression Stream
    path('stream/aggression/start/', AggressionStreamStartView.as_view(), name='stream-aggression-start'),
    path('stream/aggression/stop/', AggressionStreamStopView.as_view(), name='stream-aggression-stop'),
    path('stream/aggression/status/', AggressionStreamStatusView.as_view(), name='stream-aggression-status'),
    path('stream/aggression/feed/', aggression_stream_feed, name='stream-aggression-feed'),
]
