# Generated by Django 5.2.8 on 2026-05-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (6h-14h)'), ('AFTERNOON', 'Afternoon (14h-22h)'), ('NIGHT', 'Night (22h-6h)')], default='MORNING', max_length=20)),
                ('caregiver_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('transcription', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
