# Generated by Django 5.0 on 2026-04-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gaitobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaitobservation',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to='gait_clips/'),
        ),
    ]
