# Generated by Django 5.2.8 on 2026-04-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mealtime_incident_meal_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
