# Generated by Django 5.2.8 on 2026-04-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_isolationsession_isolationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Breakfast, Lunch, Dinner', max_length=50)),
                ('time', models.TimeField(help_text='Scheduled meal time')),
                ('expected_people', models.PositiveIntegerField(default=4, help_text='Expected number of residents')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone where the meal takes place (e.g., Dining Hall)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='core.zone')),
            ],
            options={
                'verbose_name': 'Meal Time',
                'verbose_name_plural': 'Meal Times',
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='meal',
            field=models.ForeignKey(blank=True, help_text='Only used for absence incidents tied to a meal schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_incidents', to='core.mealtime'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INCIDENT', 'Incident Alert'), ('ABSENCE', 'Meal Absence Alert'), ('HEALTH', 'Health Metric Alert'), ('INFO', 'Information')], default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.incident')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.mealtime')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.resident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
