# Generated by Django 5.0 on 2026-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gaitobservation_video_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaitobservation',
            name='video_clip',
        ),
        migrations.AddField(
            model_name='gaitobservation',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='gait_snapshots/'),
        ),
    ]
