# Generated by Django 6.0.4 on 2026-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gaitobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('FALL', 'Fall'), ('FALL_RISK', 'Fall Risk'), ('AGGRESSION', 'Aggression'), ('WANDERING', 'Wandering'), ('ABSENCE', 'Absence'), ('DISTRESS_CRY', 'Distress Cry'), ('CARDIAC', 'Cardiac')], max_length=50),
        ),
    ]
