# Generated by Django 5.0 on 2026-05-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resident_photo_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('FALL', 'Fall'), ('FALL_RISK', 'Fall Risk'), ('AGGRESSION', 'Aggression'), ('WANDERING', 'Wandering'), ('ABSENCE', 'Absence'), ('DISTRESS_CRY', 'Distress Cry'), ('CARDIAC', 'Cardiac'), ('MEDICATION_MISSED', 'Medication Missed')], max_length=50),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Metformin, Aspirin', max_length=100)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500mg', max_length=50)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('weekly', 'Weekly'), ('as_needed', 'As Needed')], default='once_daily', max_length=30)),
                ('scheduled_time', models.TimeField(help_text='Primary scheduled time e.g. 08:00')),
                ('scheduled_time_2', models.TimeField(blank=True, help_text='Second dose time (for twice daily)', null=True)),
                ('scheduled_time_3', models.TimeField(blank=True, help_text='Third dose time (for three times daily)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.resident')),
            ],
            options={
                'ordering': ['resident', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='When the medication was supposed to be taken')),
                ('actual_taken_at', models.DateTimeField(blank=True, help_text='Actual time taken — null if missed or refused', null=True)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed'), ('late', 'Late'), ('refused', 'Refused')], default='taken', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'CAREGIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_logs_created', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.medication')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='core.resident')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AdherenceRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Risk probability 0.0 (safe) to 1.0 (certain miss)')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('predicted_for', models.DateField(help_text='The date this score predicts risk for (tomorrow)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(choices=[('rule_based', 'Rule-Based'), ('xgboost', 'XGBoost')], default='rule_based', max_length=20)),
                ('adherence_rate_7d', models.FloatField(default=0.0, help_text='% taken in last 7 days')),
                ('adherence_rate_30d', models.FloatField(default=0.0, help_text='% taken in last 30 days')),
                ('meal_skips_7d', models.PositiveIntegerField(default=0)),
                ('gait_abnormal_days_7d', models.PositiveIntegerField(default=0)),
                ('isolation_days_7d', models.PositiveIntegerField(default=0)),
                ('days_since_last_fall', models.IntegerField(default=999)),
                ('contributing_factors', models.JSONField(default=list, help_text="List of factors that raised the score e.g. ['meal_skipping', 'gait_decline']")),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_scores', to='core.resident')),
            ],
            options={
                'ordering': ['-predicted_for'],
                'unique_together': {('resident', 'predicted_for')},
            },
        ),
    ]
