# Generated by Django 6.0.4 on 2026-05-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_incident_type_medication_medicationlog_and_more'),
        ('core', '0007_glucosereading'),
    ]

    operations = [
    ]
